// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace truck_manifest.T4Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DispatchT4Template : DispatchT4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 8 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
 if(ProductsDrawGrandTotalsHash.Count > 0){

 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 13 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
    if(TruckDictionary["UseHeader"] == "True"){

 
            
            #line default
            #line hidden
            this.Write("\r\n    <tr>\r\n      <td class=\"header\"  align=\"left\" colspan=\"1\">");
            
            #line 18 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TruckDictionary["RunDate"]));
            
            #line default
            #line hidden
            this.Write(@" - 5 Day - 1 Part Run</td>
      <td class=""header""  align=""center"" colspan=""9"">Post Gazette Dispatch Sheet </td>

      <td  colspan=""6"" align=""right"" class=""header"">Page: 1 </td>

    </tr>
       <tr>
      <td class=""header"" align=""left"">Created: ");
            
            #line 25 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToShortDateString()+" "+ DateTime.Now.ToLongTimeString()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td  colspan=\"5\" align=\"left\" class=\"header\"><div style=\"height: 2px" +
                    "; background-color:gray; text-align: center\">\r\n  <span style=\"background-color:#" +
                    "cccccc; position: relative; top: -0.5em; padding:2px;\">\r\n    1st Sequence\r\n  </s" +
                    "pan>\r\n</div></td>\r\n      <td colspan=\"5\" align=\"left\" class=\"header\"><div style=" +
                    "\"height: 2px; background-color: gray; text-align: center\">\r\n  <span style=\"backg" +
                    "round-color: #cccccc; position: relative; top: -0.5em;  padding:2px;\">\r\n    2nd " +
                    "Sequence\r\n  </span>\r\n</div></td>\r\n      <td colspan=\"5\" align=\"left\" class=\"head" +
                    "er\"><div style=\"height: 2px; background-color: gray; text-align: center\">\r\n  <sp" +
                    "an style=\"background-color: #cccccc; position: relative; top: -0.5em; padding:2p" +
                    "x;\">\r\n   3rd Sequence\r\n  </span>\r\n</div></td>\r\n    </tr>\r\n    <tr>\r\n      <td cl" +
                    "ass=\"header\" align=\"left\">Key Truck </td>\r\n      <td align=\"left\" class=\"header\"" +
                    ">Prod-Bs </td>\r\n      <td align=\"left\" class=\"header\">&nbsp;</td>\r\n      <td ali" +
                    "gn=\"left\" class=\"header\">Copies </td>\r\n      <td align=\"left\" class=\"header\">Bun" +
                    "ds </td>\r\n      <td align=\"left\" class=\"header\"> Odds</td>\r\n      <td align=\"lef" +
                    "t\" class=\"header\">Prod-Bs </td>\r\n      <td align=\"left\" class=\"header\">&nbsp;</t" +
                    "d>\r\n      <td align=\"left\" class=\"header\">Copies </td>\r\n      <td align=\"left\" c" +
                    "lass=\"header\">Bunds </td>\r\n      <td align=\"left\" class=\"header\">Odds</td>\r\n    " +
                    " <td align=\"left\" class=\"header\">Prod-Bs</td>\r\n      <td align=\"left\" class=\"hea" +
                    "der\">&nbsp;</td>\r\n      <td align=\"left\" class=\"header\">Copies</td>\r\n      <td a" +
                    "lign=\"left\" class=\"header\">Bunds</td>\r\n      <td align=\"left\" class=\"header\">Odd" +
                    "s</td>\r\n    </tr>\r\n    <tr>\r\n      <td class=\"header\" align=\"left\" colspan=\"16\">" +
                    "<hr /></td>\r\n    </tr>\r\n  ");
            
            #line 63 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    <tr>\r\n     \r\n      <td class=\"detail\" align=\"left\"><b>");
            
            #line 67 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TruckDictionary["ShortTruckID"]));
            
            #line default
            #line hidden
            this.Write("</b> - ");
            
            #line 67 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TruckDictionary["TruckName"] +"-"+TruckDictionary["DeliveryArea"].Split(new string[]{"<BR>"}, StringSplitOptions.None)[0]));
            
            #line default
            #line hidden
            this.Write(" </td>\r\n    \r\n\r\n         \r\n         ");
            
            #line 71 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
    
            KeyValuePair<string, Dictionary<string,Dictionary<string, int>>> lastofprodhash = ProductsDrawGrandTotalsHash.Last();
            KeyValuePair<string, Dictionary<string, int>> last = lastofprodhash.Value.Last();

            int threecount = 0;
         

			    List<string> sortedKeyList2 =  outputsort.OrderKeysPPGFirst( new List<string> (ProductsDrawGrandTotalsHash.Keys));

                        foreach(string key2 in sortedKeyList2)
                        {
                        Dictionary<string,Dictionary<string,int>> product2 = ProductsDrawGrandTotalsHash[key2];



		    List<string> paperSectionSortedKeyList =  outputsort.OrderSectionKeysPPG( new List<string> (ProductsDrawGrandTotalsHash[key2].Keys));
            
			
			foreach (string psKey in paperSectionSortedKeyList)
			{
			 Dictionary<string, int> papersection =  ProductsDrawGrandTotalsHash[key2][psKey];

			threecount++;



			if(altprod){
			if(key2 != "PPG"){
			
            
            #line default
            #line hidden
            this.Write("\r\n\r\n      <td align=\"left\" class=\"detail\"><p><b>");
            
            #line 102 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key2+"-"+ psKey));
            
            #line default
            #line hidden
            this.Write("</b></p>\r\n      </td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 104 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["StandardBundleSize"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 105 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["Draw"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 106 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["Bundles"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 107 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["Odds"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n\r\n\r\n\r\n      ");
            
            #line 112 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
 
      } else {
      threecount--;
      }
      }


      if(!altprod){
      	
            
            #line default
            #line hidden
            this.Write("\r\n\r\n      <td align=\"left\" class=\"detail\"><p><b>");
            
            #line 123 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key2+"-"+psKey));
            
            #line default
            #line hidden
            this.Write("</b></p>\r\n      </td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 125 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["StandardBundleSize"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 126 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["Draw"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 127 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["Bundles"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"left\" class=\"detail\">");
            
            #line 128 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(papersection["Odds"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n      \t");
            
            #line 130 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
 
      }


      if(threecount==3)
    { 

    threecount=0; 
            
            #line default
            #line hidden
            this.Write("    </tr>\r\n    <tr><td class=\"detail\" align=\"left\"></td>\r\n \r\n    ");
            
            #line 141 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
 }
            
            #line default
            #line hidden
            this.Write("      \r\n\r\n      ");
            
            #line 144 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
    
        }}


        string drops;
        	if(altprod){drops = TruckDictionary["AltTotalNumberOfDrops"];} else {
        	drops = TruckDictionary["TotalNumberOfDrops"];
        	}

			
            
            #line default
            #line hidden
            this.Write("         \r\n    </tr>\r\n    <tr>\r\n      <td class=\"detail\" align=\"center\">No. of Dr" +
                    "ops=");
            
            #line 157 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(drops));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td align=\"center\" colspan=\"16\"></td>\r\n    </tr>\r\n      <tr>\r\n      " +
                    "<td align=\"center\" colspan=\"18\"><hr/></td>\r\n    </tr>\r\n\r\n    ");
            
            #line 164 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
  }
 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n     ");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 168 "C:\Users\IEUser\Desktop\truckexport\T4Templates\DispatchT4Template.tt"
 
public StringDictionary TruckDictionary {get; set; }
    public Dictionary<string, Dictionary<string,Dictionary<string, int>>> ProductsDrawGrandTotalsHash {get; set;}
    public bool altprod{get; set;}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class DispatchT4TemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
