// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace truck_manifest.T4Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Collections;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class MasterPalletT4Template : MasterPalletT4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write(@"



<!DOCTYPE html PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">
<html>
<head> <title>Pallet</title>
<meta http-equiv=""Content-Type"" content=""text/html; charset=ISO-8859-1"">
<style type=""text/css"">
.mainheader {
	FONT-FAMILY: Arial;
	FONT-SIZE: 10pt;
	FONT-WEIGHT: Bold;
	background-color: LightGrey;
}
.header {
	FONT-FAMILY: Arial;
	FONT-SIZE: 8pt;
	FONT-WEIGHT: Bold;
	background-color: LightGrey;
}
.detail {
	FONT-FAMILY: Arial;
	FONT-SIZE: 8pt;    
}
</style>
</head>
<body>
<table width=""100%"" cellspacing=""0"" cellpadding=""0"">
  <tbody>
    ");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(report));
            
            #line default
            #line hidden
            this.Write("\n\n    <tr style=\"page-break-before:always;\">\n<td colspan=\"3\" class=\"mainheader\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MasterTruckDictionary["RunDate"]));
            
            #line default
            #line hidden
            this.Write(" -  ");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MasterTruckDictionary["title"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td colspan=\"6\" class=\"mainheader\">Post Gazette Pallet Report</td>\n<td cols" +
                    "pan=\"3\" class=\"mainheader\" align=\"right\"></td>\n</tr>\n<tr>\n<td colspan=\"3\" class=" +
                    "\"header\">Created: ");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToShortDateString()+" "+ DateTime.Now.ToLongTimeString()));
            
            #line default
            #line hidden
            this.Write(@"</td>
<td colspan=""6"" class=""header""></td>
<td colspan=""3"" class=""header"" align=""right"">Pallet Size: 60</td>
</tr>
<tr>
<td colspan=""10"">
<table width=""100%"" cellspacing=""0"" cellpadding=""0"">
<tbody><tr class=""header"">
<td align=""right"">Prod #</td>
<td align=""right"">Bundle Size</td>
<td align=""right"">HD Papers</td>
<td align=""right"">SC Papers</td>
<td align=""right"">Total Papers</td>
<td align=""right"">Total Bundles</td>
<td align=""right"">Full</td>
<td align=""right"">Part</td>
<td align=""right"">Part Bundles</td>
<td align=""right"">Odds</td>
<td align=""right"">Pallets</td>
</tr>




     ");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
       
	 bool color = false;
	 if  (MasterTruckDictionary["title"].Contains("Color")) color = true;
	 
	 
	 
	 foreach (KeyValuePair<string, Dictionary<string, Dictionary<string, int>>> product in ProductsMasterTotalsHash) {
              foreach (KeyValuePair<string, Dictionary<string, int>> entry in product.Value)
			{




			if( (product.Key=="PPG" && color) || (product.Key=="PPG" && entry.Key.Length == 3 && entry.Key[2] == '0')  ){
			 
            
            #line default
            #line hidden
            this.Write("\n<tr class=\"header\"><td colspan=\"11\"><hr>\n</td></tr><tr class=\"detail\">\n<td align" +
                    "=\"right\" width=\"10%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(product.Key));
            
            #line default
            #line hidden
            this.Write("-");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Key));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["StandardBundleSize"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["HomeDeliveryDraw"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["SingleCopyDraw"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["Draw"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["Bundles"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["FullPallets"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["OddPalletCount"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["OddPalletContains"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["Odds"]));
            
            #line default
            #line hidden
            this.Write("</td>\n<td align=\"right\" width=\"9%\">");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Value["Pallets"]));
            
            #line default
            #line hidden
            this.Write("</td>\n</tr>\n\t\t\t    ");
            
            #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
  }

			    }
			    }
			 
            
            #line default
            #line hidden
            this.Write("\n\n  </tbody>\n</table>\n</body>\n</html>    \n  ");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\IEUser\Desktop\truckexport\T4Templates\MasterPalletT4Template.tt"
 
public string report {get; set; }
public StringDictionary MasterTruckDictionary {get; set; }
public Dictionary<string, Dictionary<string, Dictionary<string, int>>> ProductsMasterTotalsHash {get; set;}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class MasterPalletT4TemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
